name: discord-ai
script: 'bin/main'
cwd: '/root/discord-ai'
interpreter: '/bin/bash'
exec_mode: 'fork'
instances: '1'
max_memory_restart: '260M'
instance_var: 'INSTANCE_ID'
error_file: ./error.log
out_file: ./out.log
log_file: ./log.log
env:
  TOKEN: "SOME_TOKEN"