name: Go Build Docker Build

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]
  create:
    tags: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: golang:1.22.4-bookworm
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
        with:
          show-progress: true
      - name: go build
        run: go build -o "$GITHUB_WORKSPACE/discord-ai" "$GITHUB_WORKSPACE/cmd/ai/main/main.go"
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: "discord-ai-${{ github.ref_name }}"
          path: ${{ github.workspace }}/discord-ai
          retention-days: 1
          if-no-files-found: error