name: Build

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: golang:1.22.4-bookworm
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
        with:
          show-progress: true
      - name: go build
        run: go build -o "$GITHUB_WORKSPACE/discord-ai" "$GITHUB_WORKSPACE/cmd/ai/main/main.go"
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: "discord-ai-${{ github.ref_name }}"
          path: ${{ github.workspace }}/discord-ai
          retention-days: 1
          if-no-files-found: error
  docker-build-upload:
    runs-on: ubuntu-latest
    needs: [ "build" ]
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout the Dockerfile
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            Dockerfile
            dca
          sparse-checkout-cone-mode: false
          show-progress: true
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: "discord-ai-${{ github.ref_name }}"
          path: ${{ github.workspace }}
          merge-multiple: true
      - name: fix permissions
        run: chmod 755 discord-ai && chmod 755 dca
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag "${{ vars.IMAGE_PATH }}:${{ github.ref_name }}"
      - run: ls -lh
#      - uses: kitabisa/docker-slim-action@v1
#        env:
#          DSLIM_HTTP_PROBE: false
#          DSLIM_INCLUDE_BIN: "/usr/bin/ffmpeg"
#        with:
#          target: "${{ vars.IMAGE_PATH }}:${{ github.ref_name }}"
#          overwrite: true
      #          tag: ${{ github.ref_name }}
      - name: Authenticate with Google Cloud
        uses: 'google-github-actions/auth@v2'
        id: auth
        with:
          token_format: access_token
          workload_identity_provider: ${{ vars.GCLOUD_PROVIDER }}
          service_account: ${{ vars.GCLOUD_SERVICE_ACCOUNT }}
          create_credentials_file: true
      - name: Login to Artifact Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.REGION }}-docker.pkg.dev
          username: oauth2accesstokend
          password: ${{ steps.auth.outputs.access_token }}
      - name: upload
        run: docker push ${{ vars.IMAGE_PATH }}:${{ github.ref_name }}
  helm:
    runs-on: ubuntu-latest
    container: alpine/helm:3.15.2
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            cloud
          sparse-checkout-cone-mode: false
          show-progress: true
      - run: helm lint cloud
      - run: helm template cloud --output-dir cloud/rendered
