name: deploy-cleanup

on:
  workflow_call:
    inputs:
      cleanup:
        type: boolean
        description: Delete files and deployment after deploying or not
        required: true
        default: true
  workflow_dispatch:
    inputs:
      cleanup:
        type: boolean
        description: Delete files and deployment after deploying or not
        required: true
        default: true


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Delete service to deploy a new one
        if: github.ref_type == 'tag'
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.server_ip }}
          username: ${{ vars.user }}
          password: ${{ vars.user_pass }}
          script: |
            pm2 stop ${{ vars.SERVICE }}
            sleep 1s
            pm2 delete ${{ vars.SERVICE }}
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.server_ip }}
          username: ${{ vars.user }}
          password: ${{ vars.user_pass }}
          script: pm2 start /root/${{ vars.SERVICE }}/${{ github.ref_name }}/pm2.yaml
  cleanup:
    runs-on: ubuntu-latest
    needs: [ deploy ]
    if: inputs.cleanup == true
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.server_ip }}
          username: ${{ vars.user }}
          password: ${{ vars.user_pass }}
          script: |
            pm2 stop ${{ github.ref_type == 'tag' && vars.SERVICE || format('{0}-{1}', vars.SERVICE, github.ref_name) }}
            rm -rf /root/${{ vars.SERVICE }}/${{ github.ref_name }}
            pm2 delete ${{ github.ref_type == 'tag' && vars.SERVICE || format('{0}-{1}', vars.SERVICE, github.ref_name) }}