name: Docker Image CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

jobs:

  go-build:
    runs-on: ubuntu-latest
    container:
      image: golang:1.22.4-bookworm
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
        with:
          show-progress: true
      - name: go build
        run: go build -o "$GITHUB_WORKSPACE/discord-ai" "$GITHUB_WORKSPACE/cmd/ai/main/main.go"

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: "discord-ai-${{ github.sha }}"
          path: ${{ github.workspace }}/discord-ai
          retention-days: 1
          if-no-files-found: error


  docker-build:
    runs-on: ubuntu-latest
    needs: [go-build]
    steps:
      - name: Checkout the Dockerfile
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            Dockerfile
          sparse-checkout-cone-mode: false
          show-progress: true

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: "discord-ai-${{ github.sha }}"
          path: ${{ github.workspace }}
          merge-multiple: true
      - name: Display current dir
        run: pwd
      - name: Display structure of downloaded files
        run: ls -R
      - name: Display structure of downloaded files
        run: file "discord-ai-${{ github.sha }}"

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag "$GITHUB_REPOSITORY:$GITHUB_SHA"
#  publish:
#
#    runs-on:
#    needs: [docker-build]

