name: Docker Image CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  go-build:
    runs-on: ubuntu-latest
    container:
      image: golang:1.22.4-bookworm
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
        with:
          show-progress: true
      - name: go build
        run: go build -o "$GITHUB_WORKSPACE/discord-ai" "$GITHUB_WORKSPACE/cmd/ai/main/main.go"

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: "discord-ai-${{ github.sha }}"
          path: ${{ github.workspace }}/discord-ai
          retention-days: 1
          if-no-files-found: error


  docker-build:
    runs-on: ubuntu-latest
    needs: [go-build]
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout the Dockerfile
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            Dockerfile
            dca
          sparse-checkout-cone-mode: false
          show-progress: true
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: "discord-ai-${{ github.sha }}"
          path: ${{ github.workspace }}
          merge-multiple: true
      - name: fix permissions
        run: chmod 755 discord-ai && chmod 755 dca
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag "${{ vars.IMAGE_PATH }}:$GITHUB_SHA"
      - name: Authenticate with Google Cloud
        uses: 'google-github-actions/auth@v2'
        id: auth
        with:
          token_format: access_token
          workload_identity_provider: ${{ vars.GCLOUD_PROVIDER }}
          service_account: ${{ vars.GCLOUD_SERVICE_ACCOUNT }}
          create_credentials_file: true
      - name: Login to Artifact Registry
        uses: docker/login-action@v3
        with:
          registry: me-west1-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}
      - name: upload
        run: docker push ${{ vars.IMAGE_PATH }}:${{ github.sha }}
      #        run: echo "MY_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
      - name: GitHub Tag Name example
        run: |
          echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
          echo "Tag name from github.ref_name: ${{  github.ref_name }}"
#      - name: Update cloud run service
#        id: 'deploy'
#        uses: 'google-github-actions/deploy-cloudrun@v2'
#        with:
#          service: ${{ vars.SERVICE }}
#          image: ${{ vars.IMAGE_PATH }}:${{ github.sha }}
#          region: ${{ vars.REGION }}
#          env_vars: |
#            TOKEN=${{ vars.LUNA_TOKEN }}
#      - name: bot url
#        run: echo "url at\n${{ steps.deploy.outputs.url }}"
#  publish:
#
#    runs-on:
#    needs: [docker-build]



#  s-1vcpu-512mb-10gb