name: Docker Image CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

jobs:

  go-build:
    runs-on: ubuntu-latest
    container:
      image: golang:1.22.4-bookworm
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
      - name: go build
        run: go -o discord-ai cmd/ai/main/main.go
      - name: Cache files
        uses: actions/cache@v4
        with:
          key: go-cache
          path: |
            ${{ HOME }}/go
            ${{ GITHUB_WORKSPACE }}

  docker-build:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Cache files
        uses: actions/cache@v4
        with:
          key: go-cache
          path: |
            ${{ HOME }}/go
            ${{ GITHUB_WORKSPACE }}
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag discord-ai:${{ GITHUB_SHA }}
  publish:

    runs-on:
    needs: [docker-build]

