name: Docker Image CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

jobs:

  go-build:
    runs-on: ubuntu-latest
    container:
      image: golang:1.22.4-bookworm
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
      - name: go build
        run: go build -o "$GITHUB_WORKSPACE/discord-ai" "$GITHUB_WORKSPACE/cmd/ai/main/main.go"

      - name: Cache files
        uses: actions/cache/save@v4
        with:
          key: go-cache
          path: |
            ${{ env.HOME }}/go
            ${{ env.GITHUB_WORKSPACE }}

  docker-build:
    runs-on: ubuntu-latest
    needs: [go-build]
    steps:
      - name: Cache files
        uses: actions/cache/restore@v4
        id: cache
        with:
          key: go-cache
          path: |
            ${{ env.HOME }}/go
            ${{ env.GITHUB_WORKSPACE }}

      - name: cancel if not cached
        uses: actions/github-script@v6
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          script: |
              const delay = ms => new Promise(res => setTimeout(res, ms));

              github.rest.actions.cancelWorkflowRun({
                owner: context.repo.owner,
                repo: context.repo.repo,
                run_id: context.runId
              });

              while (true) {
                core.info('Waiting for workflow to cancel ...');
                await delay(5000);
              }
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag "$GITHUB_REPOSITORY:$GITHUB_SHA"
#  publish:
#
#    runs-on:
#    needs: [docker-build]

