name: Docker Image CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  go-build:
    runs-on: ubuntu-latest
    container:
      image: golang:1.22.4-bookworm
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
        with:
          show-progress: true
      - name: go build
        run: go build -o "$GITHUB_WORKSPACE/discord-ai" "$GITHUB_WORKSPACE/cmd/ai/main/main.go"

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: "discord-ai-${{ github.sha }}"
          path: ${{ github.workspace }}/discord-ai
          retention-days: 1
          if-no-files-found: error


  docker-build:
    runs-on: ubuntu-latest
    needs: [go-build]
    steps:
      - name: Checkout the Dockerfile
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            Dockerfile
            dca
          sparse-checkout-cone-mode: false
          show-progress: true
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: "discord-ai-${{ github.sha }}"
          path: ${{ github.workspace }}
          merge-multiple: true
      - name: Display structure of downloaded files
        run: file "discord-ai-${{ github.sha }}"
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag "$GITHUB_REPOSITORY:$GITHUB_SHA"

  gcloud-deploy:
    runs-on: ubuntu-latest
    needs: [docker-build]
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Authenticate with Google Cloud
        uses: 'google-github-actions/auth@v2'
        id: auth
        with:
          workload_identity_provider: 'projects/981651558497/locations/global/workloadIdentityPools/github-actions/providers/github'
          service_account: 'fuad-a-daoud-gmail-com@digitallands-project.iam.gserviceaccount.com'
          create_credentials_file: true
      - name: Login to Artifact Registry
        uses: docker/login-action@v1
        with:
          registry: me-west1-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}
      - name: Get tag
        id: get-tag
#        run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}
        run: echo ${{ github.sha }}
      - name: Get image name
        id: image-name
        run: echo ::set-output name=image::${me-west1-docker.pkg.dev/digitallands/docker/discord-ai:${{ steps.get-tag.outputs.short_ref }}}
      - name: Tag Docker image and push to Google Artifact Registry
        uses: docker/build-push-action@v2
        id: docker-push-tagged
        with:
          push: true
          tags: ${{ steps.image-name.outputs.image }}

      - name: Update cloud run service
        id: 'deploy'
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: 'discord-ai'
          image: 'me-west1-docker.pkg.dev/digitallands-project/docker/discord-ai:v0.0.1'
          region: 'me-west1'
#  publish:
#
#    runs-on:
#    needs: [docker-build]



#  s-1vcpu-512mb-10gb