name: Docker Image CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

jobs:

  go-build:
    runs-on: ubuntu-latest
    container:
      image: golang:1.22.4-bookworm
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
      - name: go build
        run: go build -o "$GITHUB_WORKSPACE/discord-ai" "$GITHUB_WORKSPACE/cmd/ai/main/main.go"

      - name: Cache files
        uses: actions/cache/save@v4
        with:
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('$GITHUB_WORKSPACE/discord-ai') }}
          path: |
            ${{ env.HOME }}/go
            ${{ env.GITHUB_WORKSPACE }}

  docker-build:
    runs-on: ubuntu-latest
    needs: [go-build]
    steps:
      - name: Cache files
        uses: actions/cache/restore@v4
        id: cache
        with:
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('$GITHUB_WORKSPACE/discord-ai') }}
          path: |
            ${{ env.HOME }}/go
            ${{ env.GITHUB_WORKSPACE }}
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag "$GITHUB_REPOSITORY:$GITHUB_SHA"
#  publish:
#
#    runs-on:
#    needs: [docker-build]

