name: Release

on:
  workflow_run:
    workflows: [ "Docker Build Upload" ]
    tags: ["*"]
    types:
      - completed


jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Authenticate with Google Cloud
        uses: 'google-github-actions/auth@v2'
        id: auth
        with:
          token_format: access_token
          workload_identity_provider: ${{ vars.GCLOUD_PROVIDER }}
          service_account: ${{ vars.GCLOUD_SERVICE_ACCOUNT }}
          create_credentials_file: true
      - name: Update cloud run service
        id: 'deploy'
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: ${{ vars.SERVICE }}
          image: ${{ vars.IMAGE_PATH }}:${{ github.ref_name }}
          region: ${{ vars.REGION }}
          env_vars: |
            TOKEN=${{ vars.LUNA_TOKEN }}
      - name: bot url
        run: echo "url at\n${{ steps.deploy.outputs.url }}"